# Generated by Django 3.2.9 on 2021-11-14 10:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fleet')),
            ],
        ),
    ]
